//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.06 at 11:32:37 AM EEST 
//


package domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import mslib.MassSpectrum;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Link" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="Csv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *       &lt;attribute name="scanId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fileName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="precursorMZ" use="required" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *       &lt;attribute name="precursorIntensity" use="required" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "link",
    "csv"
})
@XmlRootElement(name = "Spectrum")
public class Spectrum {

    @XmlElement(name = "Link")
    @XmlSchemaType(name = "anyURI")
    protected String link;
    @XmlElement(name = "Csv")
    protected String csv;
    @XmlAttribute(name = "scanId")
    protected int scanId;
    @XmlAttribute(name = "fileName")
    protected String fileName;
    @XmlAttribute(name = "precursorMZ", required = true)
    protected Double precursorMZ;
    @XmlAttribute(name = "precursorIntensity", required = true)
    protected Double precursorIntensity;

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the csv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsv() {
        return csv;
    }

    /**
     * Sets the value of the csv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsv(String value) {
        this.csv = value;
    }

    /**
     * Gets the value of the scanId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public int getScanId() {
        return scanId;
    }

    /**
     * Sets the value of the scanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScanId(int value) {
        this.scanId = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the precursorMZ property.
     * 
     */
    public Double getPrecursorMZ() {
        return precursorMZ;
    }

    /**
     * Sets the value of the precursorMZ property.
     * 
     */
    public void setPrecursorMZ(Double value) {
        this.precursorMZ = value;
    }

    /**
     * Gets the value of the precursorIntensity property.
     * 
     */
    public Double getPrecursorIntensity() {
        return precursorIntensity;
    }

    /**
     * Sets the value of the precursorIntensity property.
     * 
     */
    public void setPrecursorIntensity(Double value) {
        this.precursorIntensity = value;
    }

}
