//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.06 at 11:32:37 AM EEST 
//


package tr.edu.iyte.dnmso.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ModAminoAcid">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="character" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="monoIsotopicMass" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *                 &lt;attribute name="averageMass" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Terminal">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="front" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="back" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mass" use="required" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modAminoAcid",
    "terminal"
})
@XmlRootElement(name = "Modification")
public class Modification {

    @XmlElement(name = "ModAminoAcid")
    protected Modification.ModAminoAcid modAminoAcid;
    @XmlElement(name = "Terminal")
    protected Modification.Terminal terminal;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "mass", required = true)
    protected Double mass;

    /**
     * Gets the value of the modAminoAcid property.
     * 
     * @return
     *     possible object is
     *     {@link Modification.ModAminoAcid }
     *     
     */
    public Modification.ModAminoAcid getModAminoAcid() {
        return modAminoAcid;
    }

    /**
     * Sets the value of the modAminoAcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modification.ModAminoAcid }
     *     
     */
    public void setModAminoAcid(Modification.ModAminoAcid value) {
        this.modAminoAcid = value;
    }

    /**
     * Gets the value of the terminal property.
     * 
     * @return
     *     possible object is
     *     {@link Modification.Terminal }
     *     
     */
    public Modification.Terminal getTerminal() {
        return terminal;
    }

    /**
     * Sets the value of the terminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modification.Terminal }
     *     
     */
    public void setTerminal(Modification.Terminal value) {
        this.terminal = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     */
    public Double getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     */
    public void setMass(Double value) {
        this.mass = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="character" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="monoIsotopicMass" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *       &lt;attribute name="averageMass" type="{http://www.w3.org/2001/XMLSchema}Double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ModAminoAcid {

        @XmlAttribute(name = "character", required = true)
        protected String character;
        @XmlAttribute(name = "monoIsotopicMass")
        protected Double monoIsotopicMass;
        @XmlAttribute(name = "averageMass")
        protected Double averageMass;

        /**
         * Gets the value of the character property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCharacter() {
            return character;
        }

        /**
         * Sets the value of the character property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCharacter(String value) {
            this.character = value;
        }

        /**
         * Gets the value of the monoIsotopicMass property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getMonoIsotopicMass() {
            return monoIsotopicMass;
        }

        /**
         * Sets the value of the monoIsotopicMass property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setMonoIsotopicMass(Double value) {
            this.monoIsotopicMass = value;
        }

        /**
         * Gets the value of the averageMass property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getAverageMass() {
            return averageMass;
        }

        /**
         * Sets the value of the averageMass property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setAverageMass(Double value) {
            this.averageMass = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="front" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="back" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Terminal {

        @XmlAttribute(name = "front", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String front;
        @XmlAttribute(name = "back", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String back;

        /**
         * Gets the value of the front property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFront() {
            return front;
        }

        /**
         * Sets the value of the front property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFront(String value) {
            this.front = value;
        }

        /**
         * Gets the value of the back property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBack() {
            return back;
        }

        /**
         * Sets the value of the back property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBack(String value) {
            this.back = value;
        }

    }

}
