//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.06 at 11:32:37 AM EEST 
//


package tr.edu.iyte.dnmso.domain;


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Proof" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="modificationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pos" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="confidence" use="required" type="{http://www.w3.org/2001/XMLSchema}Double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proof",
    "modificationName"
})
@XmlRootElement(name = "ModifiedAminoAcid")
public class ModifiedAminoAcid {

    @XmlElement(name = "Proof")
    protected List<Proof> proof;
    @XmlElement(required = true)
    protected String modificationName;
    @XmlAttribute(name = "pos", required = true)
    protected Integer pos;
    @XmlAttribute(name = "confidence", required = true)
    protected Double confidence;

    /**
     * Gets the value of the proof property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the proof property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProof().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Proof }
     * 
     * 
     */
    public List<Proof> getProof() {
        if (proof == null) {
            proof = new ArrayList<Proof>();
        }
        return this.proof;
    }

    /**
     * Gets the value of the modificationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationName() {
        return modificationName;
    }

    /**
     * Sets the value of the modificationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationName(String value) {
        this.modificationName = value;
    }

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPos(Integer value) {
        this.pos = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     */
    public Double getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     */
    public void setConfidence(Double value) {
        this.confidence = value;
    }

}
