//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.06 at 11:32:37 AM EEST 
//


package tr.edu.iyte.dnmso.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tr.edu.iyte.dnmso.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tr.edu.iyte.dnmso.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Prediction }
     * 
     */
    public Prediction createPrediction() {
        return new Prediction();
    }

    /**
     * Create an instance of {@link DNMSO }
     * 
     */
    public DNMSO createDNML() {
        return new DNMSO();
    }

    /**
     * Create an instance of {@link Modification }
     * 
     */
    public Modification createModification() {
        return new Modification();
    }

    /**
     * Create an instance of {@link DNMSO.Predictions }
     * 
     */
    public DNMSO.Predictions createDNMLPredictions() {
        return new DNMSO.Predictions();
    }

    /**
     * Create an instance of {@link DNMSO.Predictions.Software }
     * 
     */
    public DNMSO.Predictions.Software createDNMLPredictionsSoftware() {
        return new DNMSO.Predictions.Software();
    }

    /**
     * Create an instance of {@link DNMSO.Predictions.Software.Settings }
     * 
     */
    public DNMSO.Predictions.Software.Settings createDNMLPredictionsSoftwareSettings() {
        return new DNMSO.Predictions.Software.Settings();
    }

    /**
     * Create an instance of {@link Prediction.Sequence }
     * 
     */
    public Prediction.Sequence createPredictionSequence() {
        return new Prediction.Sequence();
    }

    /**
     * Create an instance of {@link Prediction.Sources }
     * 
     */
    public Prediction.Sources createPredictionSources() {
        return new Prediction.Sources();
    }

    /**
     * Create an instance of {@link Prediction.Score }
     * 
     */
    public Prediction.Score createPredictionScore() {
        return new Prediction.Score();
    }

    /**
     * Create an instance of {@link AminoAcid }
     * 
     */
    public AminoAcid createAminoAcid() {
        return new AminoAcid();
    }

    /**
     * Create an instance of {@link Proof }
     * 
     */
    public Proof createProof() {
        return new Proof();
    }

    /**
     * Create an instance of {@link ModifiedAminoAcid }
     * 
     */
    public ModifiedAminoAcid createModifiedAminoAcid() {
        return new ModifiedAminoAcid();
    }

    /**
     * Create an instance of {@link Spectrum }
     * 
     */
    public Spectrum createSpectrum() {
        return new Spectrum();
    }

    /**
     * Create an instance of {@link DNMSO.Spectra }
     * 
     */
    public DNMSO.Spectra createDNMLSpectra() {
        return new DNMSO.Spectra();
    }

    /**
     * Create an instance of {@link DNMSO.Modifications }
     * 
     */
    public DNMSO.Modifications createDNMLModifications() {
        return new DNMSO.Modifications();
    }

    /**
     * Create an instance of {@link Modification.ModAminoAcid }
     * 
     */
    public Modification.ModAminoAcid createModificationModAminoAcid() {
        return new Modification.ModAminoAcid();
    }

    /**
     * Create an instance of {@link Modification.Terminal }
     * 
     */
    public Modification.Terminal createModificationTerminal() {
        return new Modification.Terminal();
    }

    /**
     * Create an instance of {@link DNMSO.Predictions.Software.Settings.Setting }
     * 
     */
    public DNMSO.Predictions.Software.Settings.Setting createDNMLPredictionsSoftwareSettingsSetting() {
        return new DNMSO.Predictions.Software.Settings.Setting();
    }

    /**
     * Create an instance of {@link Prediction.Sequence.Gap }
     * 
     */
    public Prediction.Sequence.Gap createPredictionSequenceGap() {
        return new Prediction.Sequence.Gap();
    }

    /**
     * Create an instance of {@link Prediction.Sources.Source }
     * 
     */
    public Prediction.Sources.Source createPredictionSourcesSource() {
        return new Prediction.Sources.Source();
    }

}
