//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.06 at 01:15:28 PM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for activationMethodType. <p>The following schema fragment specifies the expected content contained within this class. <p> <pre> &lt;simpleType name="activationMethodType"> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"> &lt;enumeration value="ETD"/> &lt;enumeration value="ECD"/> &lt;enumeration value="CID"/> &lt;enumeration value="ETD/CID"/> &lt;enumeration value="HCD"/> &lt;/restriction> &lt;/simpleType> </pre>
 */
@XmlType(name = "activationMethodType")
@XmlEnum
public enum ActivationMethodType {

    /**
	 * @uml.property  name="eTD"
	 * @uml.associationEnd  
	 */
    ETD("ETD"),
    /**
	 * @uml.property  name="eCD"
	 * @uml.associationEnd  
	 */
    ECD("ECD"),
    /**
	 * @uml.property  name="cID"
	 * @uml.associationEnd  
	 */
    CID("CID"),
    /**
	 * @uml.property  name="eTD_CID"
	 * @uml.associationEnd  
	 */
    @XmlEnumValue("ETD/CID")
    ETD_CID("ETD/CID"),
    /**
	 * @uml.property  name="hCD"
	 * @uml.associationEnd  
	 */
    HCD("HCD");
    private final String value;

    ActivationMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActivationMethodType fromValue(String v) {
        for (ActivationMethodType c: ActivationMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
