//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="quant_label_masses" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="static_quant_label" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "asapratio_timestamp")
public class AsapratioTimestamp {

    /**
	 * @uml.property  name="quantLabelMasses"
	 */
    @XmlAttribute(name = "quant_label_masses")
    protected String quantLabelMasses;
    /**
	 * @uml.property  name="staticQuantLabel"
	 */
    @XmlAttribute(name = "static_quant_label")
    protected String staticQuantLabel;

    /**
	 * Gets the value of the quantLabelMasses property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="quantLabelMasses"
	 */
    public String getQuantLabelMasses() {
        return quantLabelMasses;
    }

    /**
	 * Sets the value of the quantLabelMasses property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="quantLabelMasses"
	 */
    public void setQuantLabelMasses(String value) {
        this.quantLabelMasses = value;
    }

    /**
	 * Gets the value of the staticQuantLabel property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="staticQuantLabel"
	 */
    public String getStaticQuantLabel() {
        return staticQuantLabel;
    }

    /**
	 * Sets the value of the staticQuantLabel property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="staticQuantLabel"
	 */
    public void setStaticQuantLabel(String value) {
        this.staticQuantLabel = value;
    }

}
