//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element ref="{http://regis-web.systemsbiology.net/pepXML}asapratio_lc_lightpeak"/> &lt;element ref="{http://regis-web.systemsbiology.net/pepXML}asapratio_lc_heavypeak"/> &lt;/sequence> &lt;attribute name="ratio" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="error" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="charge" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /> &lt;attribute name="use" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "asapratioLcLightpeak",
    "asapratioLcHeavypeak"
})
@XmlRootElement(name = "asapratio_contribution")
public class AsapratioContribution {

    /**
	 * @uml.property  name="asapratioLcLightpeak"
	 * @uml.associationEnd  
	 */
    @XmlElement(name = "asapratio_lc_lightpeak", required = true)
    protected AsapratioLcLightpeak asapratioLcLightpeak;
    /**
	 * @uml.property  name="asapratioLcHeavypeak"
	 * @uml.associationEnd  
	 */
    @XmlElement(name = "asapratio_lc_heavypeak", required = true)
    protected AsapratioLcHeavypeak asapratioLcHeavypeak;
    /**
	 * @uml.property  name="ratio"
	 */
    @XmlAttribute(required = true)
    protected float ratio;
    /**
	 * @uml.property  name="error"
	 */
    @XmlAttribute(required = true)
    protected float error;
    /**
	 * @uml.property  name="charge"
	 */
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger charge;
    /**
	 * @uml.property  name="use"
	 */
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short use;

    /**
	 * Gets the value of the asapratioLcLightpeak property.
	 * @return  possible object is {@link AsapratioLcLightpeak  }
	 * @uml.property  name="asapratioLcLightpeak"
	 */
    public AsapratioLcLightpeak getAsapratioLcLightpeak() {
        return asapratioLcLightpeak;
    }

    /**
	 * Sets the value of the asapratioLcLightpeak property.
	 * @param value  allowed object is {@link AsapratioLcLightpeak  }
	 * @uml.property  name="asapratioLcLightpeak"
	 */
    public void setAsapratioLcLightpeak(AsapratioLcLightpeak value) {
        this.asapratioLcLightpeak = value;
    }

    /**
	 * Gets the value of the asapratioLcHeavypeak property.
	 * @return  possible object is {@link AsapratioLcHeavypeak  }
	 * @uml.property  name="asapratioLcHeavypeak"
	 */
    public AsapratioLcHeavypeak getAsapratioLcHeavypeak() {
        return asapratioLcHeavypeak;
    }

    /**
	 * Sets the value of the asapratioLcHeavypeak property.
	 * @param value  allowed object is {@link AsapratioLcHeavypeak  }
	 * @uml.property  name="asapratioLcHeavypeak"
	 */
    public void setAsapratioLcHeavypeak(AsapratioLcHeavypeak value) {
        this.asapratioLcHeavypeak = value;
    }

    /**
	 * Gets the value of the ratio property.
	 * @uml.property  name="ratio"
	 */
    public float getRatio() {
        return ratio;
    }

    /**
	 * Sets the value of the ratio property.
	 * @uml.property  name="ratio"
	 */
    public void setRatio(float value) {
        this.ratio = value;
    }

    /**
	 * Gets the value of the error property.
	 * @uml.property  name="error"
	 */
    public float getError() {
        return error;
    }

    /**
	 * Sets the value of the error property.
	 * @uml.property  name="error"
	 */
    public void setError(float value) {
        this.error = value;
    }

    /**
	 * Gets the value of the charge property.
	 * @return  possible object is {@link BigInteger  }  
	 * @uml.property  name="charge"
	 */
    public BigInteger getCharge() {
        return charge;
    }

    /**
	 * Sets the value of the charge property.
	 * @param value  allowed object is {@link BigInteger  }  
	 * @uml.property  name="charge"
	 */
    public void setCharge(BigInteger value) {
        this.charge = value;
    }

    /**
	 * Gets the value of the use property.
	 * @uml.property  name="use"
	 */
    public short getUse() {
        return use;
    }

    /**
	 * Sets the value of the use property.
	 * @uml.property  name="use"
	 */
    public void setUse(short value) {
        this.use = value;
    }

}
