//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" /> &lt;attribute name="left_valley" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /> &lt;attribute name="right_valley" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /> &lt;attribute name="background" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="area" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="area_error" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="time" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="time_width" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="is_heavy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "asapratio_lc_lightpeak")
public class AsapratioLcLightpeak {

    /**
	 * @uml.property  name="status"
	 */
    @XmlAttribute(required = true)
    protected byte status;
    /**
	 * @uml.property  name="leftValley"
	 */
    @XmlAttribute(name = "left_valley", required = true)
    protected int leftValley;
    /**
	 * @uml.property  name="rightValley"
	 */
    @XmlAttribute(name = "right_valley", required = true)
    protected int rightValley;
    /**
	 * @uml.property  name="background"
	 */
    @XmlAttribute(required = true)
    protected float background;
    /**
	 * @uml.property  name="area"
	 */
    @XmlAttribute(required = true)
    protected float area;
    /**
	 * @uml.property  name="areaError"
	 */
    @XmlAttribute(name = "area_error", required = true)
    protected float areaError;
    /**
	 * @uml.property  name="time"
	 */
    @XmlAttribute(required = true)
    protected float time;
    /**
	 * @uml.property  name="timeWidth"
	 */
    @XmlAttribute(name = "time_width", required = true)
    protected float timeWidth;
    /**
	 * @uml.property  name="isHeavy"
	 */
    @XmlAttribute(name = "is_heavy", required = true)
    protected String isHeavy;

    /**
	 * Gets the value of the status property.
	 * @uml.property  name="status"
	 */
    public byte getStatus() {
        return status;
    }

    /**
	 * Sets the value of the status property.
	 * @uml.property  name="status"
	 */
    public void setStatus(byte value) {
        this.status = value;
    }

    /**
	 * Gets the value of the leftValley property.
	 * @uml.property  name="leftValley"
	 */
    public int getLeftValley() {
        return leftValley;
    }

    /**
	 * Sets the value of the leftValley property.
	 * @uml.property  name="leftValley"
	 */
    public void setLeftValley(int value) {
        this.leftValley = value;
    }

    /**
	 * Gets the value of the rightValley property.
	 * @uml.property  name="rightValley"
	 */
    public int getRightValley() {
        return rightValley;
    }

    /**
	 * Sets the value of the rightValley property.
	 * @uml.property  name="rightValley"
	 */
    public void setRightValley(int value) {
        this.rightValley = value;
    }

    /**
	 * Gets the value of the background property.
	 * @uml.property  name="background"
	 */
    public float getBackground() {
        return background;
    }

    /**
	 * Sets the value of the background property.
	 * @uml.property  name="background"
	 */
    public void setBackground(float value) {
        this.background = value;
    }

    /**
	 * Gets the value of the area property.
	 * @uml.property  name="area"
	 */
    public float getArea() {
        return area;
    }

    /**
	 * Sets the value of the area property.
	 * @uml.property  name="area"
	 */
    public void setArea(float value) {
        this.area = value;
    }

    /**
	 * Gets the value of the areaError property.
	 * @uml.property  name="areaError"
	 */
    public float getAreaError() {
        return areaError;
    }

    /**
	 * Sets the value of the areaError property.
	 * @uml.property  name="areaError"
	 */
    public void setAreaError(float value) {
        this.areaError = value;
    }

    /**
	 * Gets the value of the time property.
	 * @uml.property  name="time"
	 */
    public float getTime() {
        return time;
    }

    /**
	 * Sets the value of the time property.
	 * @uml.property  name="time"
	 */
    public void setTime(float value) {
        this.time = value;
    }

    /**
	 * Gets the value of the timeWidth property.
	 * @uml.property  name="timeWidth"
	 */
    public float getTimeWidth() {
        return timeWidth;
    }

    /**
	 * Sets the value of the timeWidth property.
	 * @uml.property  name="timeWidth"
	 */
    public void setTimeWidth(float value) {
        this.timeWidth = value;
    }

    /**
	 * Gets the value of the isHeavy property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="isHeavy"
	 */
    public String getIsHeavy() {
        return isHeavy;
    }

    /**
	 * Sets the value of the isHeavy property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="isHeavy"
	 */
    public void setIsHeavy(String value) {
        this.isHeavy = value;
    }

}
