//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for engineType. <p>The following schema fragment specifies the expected content contained within this class. <p> <pre> &lt;simpleType name="engineType"> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"> &lt;enumeration value="SEQUEST"/> &lt;enumeration value="MASCOT"/> &lt;enumeration value="COMET"/> &lt;enumeration value="PROBID"/> &lt;/restriction> &lt;/simpleType> </pre>
 */
@XmlType(name = "engineType")
@XmlEnum
public enum EngineType {

    /**
	 * @uml.property  name="sEQUEST"
	 * @uml.associationEnd  
	 */
    SEQUEST,
    /**
	 * @uml.property  name="mASCOT"
	 * @uml.associationEnd  
	 */
    MASCOT,
    /**
	 * @uml.property  name="cOMET"
	 * @uml.associationEnd  
	 */
    COMET,
    /**
	 * @uml.property  name="pROBID"
	 * @uml.associationEnd  
	 */
    PROBID;

    public String value() {
        return name();
    }

    public static EngineType fromValue(String v) {
        return valueOf(v);
    }

}
