//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element name="inputfile" maxOccurs="unbounded"> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> &lt;/element> &lt;/sequence> &lt;attribute name="filename" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="directory" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputfile"
})
@XmlRootElement(name = "interact_summary")
public class InteractSummary {

    /**
	 * @uml.property  name="inputfile"
	 */
    @XmlElement(required = true)
    protected List<Inputfile> inputfile;
    /**
	 * @uml.property  name="filename"
	 */
    @XmlAttribute(required = true)
    protected String filename;
    /**
	 * @uml.property  name="directory"
	 */
    @XmlAttribute(required = true)
    protected String directory;

    /**
	 * Gets the value of the inputfile property. <p> This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the inputfile property. <p> For example, to add a new item, do as follows: <pre> getInputfile().add(newItem); </pre> <p> Objects of the following type(s) are allowed in the list {@link Inputfile  }
	 * @uml.property  name="inputfile"
	 */
    public List<Inputfile> getInputfile() {
        if (inputfile == null) {
            inputfile = new ArrayList<Inputfile>();
        }
        return this.inputfile;
    }

    /**
	 * Gets the value of the filename property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="filename"
	 */
    public String getFilename() {
        return filename;
    }

    /**
	 * Sets the value of the filename property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="filename"
	 */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
	 * Gets the value of the directory property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="directory"
	 */
    public String getDirectory() {
        return directory;
    }

    /**
	 * Sets the value of the directory property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="directory"
	 */
    public void setDirectory(String value) {
        this.directory = value;
    }


    /**
	 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
	 */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Inputfile {

        /**
		 * @uml.property  name="name"
		 */
        @XmlAttribute(required = true)
        protected String name;

        /**
		 * Gets the value of the name property.
		 * @return  possible object is {@link String  }  
		 * @uml.property  name="name"
		 */
        public String getName() {
            return name;
        }

        /**
		 * Sets the value of the name property.
		 * @param value  allowed object is {@link String  }  
		 * @uml.property  name="name"
		 */
        public void setName(String value) {
            this.name = value;
        }

    }

}
