//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element name="intensity" maxOccurs="unbounded"> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/pepXML}positiveInt" /> &lt;attribute name="target_mass" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="absolute" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="normalized" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="reject" type="{http://www.w3.org/2001/XMLSchema}boolean" default="0" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> &lt;/element> &lt;/sequence> &lt;attribute name="is_rejected" type="{http://www.w3.org/2001/XMLSchema}boolean" default="0" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "intensity"
})
@XmlRootElement(name = "libra_result")
public class LibraResult {

    /**
	 * @uml.property  name="intensity"
	 */
    @XmlElement(required = true)
    protected List<Intensity> intensity;
    /**
	 * @uml.property  name="isRejected"
	 */
    @XmlAttribute(name = "is_rejected")
    protected Boolean isRejected;

    /**
	 * Gets the value of the intensity property. <p> This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the intensity property. <p> For example, to add a new item, do as follows: <pre> getIntensity().add(newItem); </pre> <p> Objects of the following type(s) are allowed in the list {@link Intensity  }
	 * @uml.property  name="intensity"
	 */
    public List<Intensity> getIntensity() {
        if (intensity == null) {
            intensity = new ArrayList<Intensity>();
        }
        return this.intensity;
    }

    /**
	 * Gets the value of the isRejected property.
	 * @return  possible object is {@link Boolean  }  
	 * @uml.property  name="isRejected"
	 */
    public boolean getIsRejected() {
        if (isRejected == null) {
            return false;
        } else {
            return isRejected;
        }
    }

    /**
	 * Sets the value of the isRejected property.
	 * @param value  allowed object is {@link Boolean  }  
	 * @uml.property  name="isRejected"
	 */
    public void setIsRejected(Boolean value) {
        this.isRejected = value;
    }


    /**
	 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/pepXML}positiveInt" /> &lt;attribute name="target_mass" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="absolute" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="normalized" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="reject" type="{http://www.w3.org/2001/XMLSchema}boolean" default="0" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
	 */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Intensity {

        /**
		 * @uml.property  name="channel"
		 */
        @XmlAttribute(required = true)
        protected long channel;
        /**
		 * @uml.property  name="targetMass"
		 */
        @XmlAttribute(name = "target_mass", required = true)
        protected float targetMass;
        /**
		 * @uml.property  name="absolute"
		 */
        @XmlAttribute(required = true)
        protected float absolute;
        /**
		 * @uml.property  name="normalized"
		 */
        @XmlAttribute(required = true)
        protected float normalized;
        /**
		 * @uml.property  name="reject"
		 */
        @XmlAttribute
        protected Boolean reject;

        /**
		 * Gets the value of the channel property.
		 * @uml.property  name="channel"
		 */
        public long getChannel() {
            return channel;
        }

        /**
		 * Sets the value of the channel property.
		 * @uml.property  name="channel"
		 */
        public void setChannel(long value) {
            this.channel = value;
        }

        /**
		 * Gets the value of the targetMass property.
		 * @uml.property  name="targetMass"
		 */
        public float getTargetMass() {
            return targetMass;
        }

        /**
		 * Sets the value of the targetMass property.
		 * @uml.property  name="targetMass"
		 */
        public void setTargetMass(float value) {
            this.targetMass = value;
        }

        /**
		 * Gets the value of the absolute property.
		 * @uml.property  name="absolute"
		 */
        public float getAbsolute() {
            return absolute;
        }

        /**
		 * Sets the value of the absolute property.
		 * @uml.property  name="absolute"
		 */
        public void setAbsolute(float value) {
            this.absolute = value;
        }

        /**
		 * Gets the value of the normalized property.
		 * @uml.property  name="normalized"
		 */
        public float getNormalized() {
            return normalized;
        }

        /**
		 * Sets the value of the normalized property.
		 * @uml.property  name="normalized"
		 */
        public void setNormalized(float value) {
            this.normalized = value;
        }

        /**
		 * Gets the value of the reject property.
		 * @return  possible object is {@link Boolean  }  
		 * @uml.property  name="reject"
		 */
        public boolean getReject() {
            if (reject == null) {
                return false;
            } else {
                return reject;
            }
        }

        /**
		 * Sets the value of the reject property.
		 * @param value  allowed object is {@link Boolean  }  
		 * @uml.property  name="reject"
		 */
        public void setReject(Boolean value) {
            this.reject = value;
        }

    }

}
