//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for massType. <p>The following schema fragment specifies the expected content contained within this class. <p> <pre> &lt;simpleType name="massType"> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"> &lt;enumeration value="monoisotopic"/> &lt;enumeration value="average"/> &lt;/restriction> &lt;/simpleType> </pre>
 */
@XmlType(name = "massType")
@XmlEnum
public enum MassType {

    /**
	 * @uml.property  name="mONOISOTOPIC"
	 * @uml.associationEnd  
	 */
    @XmlEnumValue("monoisotopic")
    MONOISOTOPIC("monoisotopic"),
    /**
	 * @uml.property  name="aVERAGE"
	 * @uml.associationEnd  
	 */
    @XmlEnumValue("average")
    AVERAGE("average");
    private final String value;

    MassType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MassType fromValue(String v) {
        for (MassType c: MassType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
