//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for model_dis_type. <p>The following schema fragment specifies the expected content contained within this class. <p> <pre> &lt;simpleType name="model_dis_type"> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"> &lt;enumeration value="discrete"/> &lt;enumeration value="gaussian"/> &lt;enumeration value="extremevalue"/> &lt;enumeration value="gamma"/> &lt;enumeration value="evd"/> &lt;/restriction> &lt;/simpleType> </pre>
 */
@XmlType(name = "model_dis_type")
@XmlEnum
public enum ModelDisType {

    /**
	 * @uml.property  name="dISCRETE"
	 * @uml.associationEnd  
	 */
    @XmlEnumValue("discrete")
    DISCRETE("discrete"),
    /**
	 * @uml.property  name="gAUSSIAN"
	 * @uml.associationEnd  
	 */
    @XmlEnumValue("gaussian")
    GAUSSIAN("gaussian"),
    /**
	 * @uml.property  name="eXTREMEVALUE"
	 * @uml.associationEnd  
	 */
    @XmlEnumValue("extremevalue")
    EXTREMEVALUE("extremevalue"),
    /**
	 * @uml.property  name="gAMMA"
	 * @uml.associationEnd  
	 */
    @XmlEnumValue("gamma")
    GAMMA("gamma"),
    /**
	 * @uml.property  name="eVD"
	 * @uml.associationEnd  
	 */
    @XmlEnumValue("evd")
    EVD("evd");
    private final String value;

    ModelDisType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ModelDisType fromValue(String v) {
        for (ModelDisType c: ModelDisType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
