//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://regis-web.systemsbiology.net/pepXML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package domain.pepxml;
