//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="same_scan_range" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="labeled_residues" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="xpress_light" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /> &lt;attribute name="massdiff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="masstol" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "xpressratio_summary")
public class XpressratioSummary {

    /**
	 * @uml.property  name="version"
	 */
    @XmlAttribute(required = true)
    protected String version;
    /**
	 * @uml.property  name="author"
	 */
    @XmlAttribute(required = true)
    protected String author;
    /**
	 * @uml.property  name="sameScanRange"
	 */
    @XmlAttribute(name = "same_scan_range", required = true)
    protected String sameScanRange;
    /**
	 * @uml.property  name="labeledResidues"
	 */
    @XmlAttribute(name = "labeled_residues", required = true)
    protected String labeledResidues;
    /**
	 * @uml.property  name="xpressLight"
	 */
    @XmlAttribute(name = "xpress_light", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long xpressLight;
    /**
	 * @uml.property  name="massdiff"
	 */
    @XmlAttribute(required = true)
    protected String massdiff;
    /**
	 * @uml.property  name="masstol"
	 */
    @XmlAttribute(required = true)
    protected float masstol;

    /**
	 * Gets the value of the version property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="version"
	 */
    public String getVersion() {
        return version;
    }

    /**
	 * Sets the value of the version property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="version"
	 */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
	 * Gets the value of the author property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="author"
	 */
    public String getAuthor() {
        return author;
    }

    /**
	 * Sets the value of the author property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="author"
	 */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
	 * Gets the value of the sameScanRange property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="sameScanRange"
	 */
    public String getSameScanRange() {
        return sameScanRange;
    }

    /**
	 * Sets the value of the sameScanRange property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="sameScanRange"
	 */
    public void setSameScanRange(String value) {
        this.sameScanRange = value;
    }

    /**
	 * Gets the value of the labeledResidues property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="labeledResidues"
	 */
    public String getLabeledResidues() {
        return labeledResidues;
    }

    /**
	 * Sets the value of the labeledResidues property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="labeledResidues"
	 */
    public void setLabeledResidues(String value) {
        this.labeledResidues = value;
    }

    /**
	 * Gets the value of the xpressLight property.
	 * @uml.property  name="xpressLight"
	 */
    public long getXpressLight() {
        return xpressLight;
    }

    /**
	 * Sets the value of the xpressLight property.
	 * @uml.property  name="xpressLight"
	 */
    public void setXpressLight(long value) {
        this.xpressLight = value;
    }

    /**
	 * Gets the value of the massdiff property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="massdiff"
	 */
    public String getMassdiff() {
        return massdiff;
    }

    /**
	 * Sets the value of the massdiff property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="massdiff"
	 */
    public void setMassdiff(String value) {
        this.massdiff = value;
    }

    /**
	 * Gets the value of the masstol property.
	 * @uml.property  name="masstol"
	 */
    public float getMasstol() {
        return masstol;
    }

    /**
	 * Sets the value of the masstol property.
	 * @uml.property  name="masstol"
	 */
    public void setMasstol(float value) {
        this.masstol = value;
    }

}
