//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="xpress_light" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "xpressratio_timestamp")
public class XpressratioTimestamp {

    /**
	 * @uml.property  name="xpressLight"
	 */
    @XmlAttribute(name = "xpress_light", required = true)
    protected BigInteger xpressLight;

    /**
	 * Gets the value of the xpressLight property.
	 * @return  possible object is {@link BigInteger  }  
	 * @uml.property  name="xpressLight"
	 */
    public BigInteger getXpressLight() {
        return xpressLight;
    }

    /**
	 * Sets the value of the xpressLight property.
	 * @param value  allowed object is {@link BigInteger  }  
	 * @uml.property  name="xpressLight"
	 */
    public void setXpressLight(BigInteger value) {
        this.xpressLight = value;
    }

}
