//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:34:54 AM EEST 
//


package domain.pepxml;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type. <p>The following schema fragment specifies the expected content contained within this class. <pre> &lt;complexType> &lt;complexContent> &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;attribute name="light_firstscan" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /> &lt;attribute name="light_lastscan" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /> &lt;attribute name="light_mass" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="heavy_firstscan" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /> &lt;attribute name="heavy_lastscan" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" /> &lt;attribute name="heavy_mass" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="mass_tol" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="ratio" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="heavy2light_ratio" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> &lt;attribute name="light_area" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="heavy_area" use="required" type="{http://www.w3.org/2001/XMLSchema}float" /> &lt;attribute name="decimal_ratio" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /> &lt;/restriction> &lt;/complexContent> &lt;/complexType> </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "xpressratio_result")
public class XpressratioResult {

    /**
	 * @uml.property  name="lightFirstscan"
	 */
    @XmlAttribute(name = "light_firstscan", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long lightFirstscan;
    /**
	 * @uml.property  name="lightLastscan"
	 */
    @XmlAttribute(name = "light_lastscan", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long lightLastscan;
    /**
	 * @uml.property  name="lightMass"
	 */
    @XmlAttribute(name = "light_mass", required = true)
    protected float lightMass;
    /**
	 * @uml.property  name="heavyFirstscan"
	 */
    @XmlAttribute(name = "heavy_firstscan", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long heavyFirstscan;
    /**
	 * @uml.property  name="heavyLastscan"
	 */
    @XmlAttribute(name = "heavy_lastscan", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long heavyLastscan;
    /**
	 * @uml.property  name="heavyMass"
	 */
    @XmlAttribute(name = "heavy_mass", required = true)
    protected float heavyMass;
    /**
	 * @uml.property  name="massTol"
	 */
    @XmlAttribute(name = "mass_tol", required = true)
    protected float massTol;
    /**
	 * @uml.property  name="ratio"
	 */
    @XmlAttribute(required = true)
    protected String ratio;
    /**
	 * @uml.property  name="heavy2LightRatio"
	 */
    @XmlAttribute(name = "heavy2light_ratio", required = true)
    protected String heavy2LightRatio;
    /**
	 * @uml.property  name="lightArea"
	 */
    @XmlAttribute(name = "light_area", required = true)
    protected float lightArea;
    /**
	 * @uml.property  name="heavyArea"
	 */
    @XmlAttribute(name = "heavy_area", required = true)
    protected float heavyArea;
    /**
	 * @uml.property  name="decimalRatio"
	 */
    @XmlAttribute(name = "decimal_ratio", required = true)
    protected BigDecimal decimalRatio;

    /**
	 * Gets the value of the lightFirstscan property.
	 * @uml.property  name="lightFirstscan"
	 */
    public long getLightFirstscan() {
        return lightFirstscan;
    }

    /**
	 * Sets the value of the lightFirstscan property.
	 * @uml.property  name="lightFirstscan"
	 */
    public void setLightFirstscan(long value) {
        this.lightFirstscan = value;
    }

    /**
	 * Gets the value of the lightLastscan property.
	 * @uml.property  name="lightLastscan"
	 */
    public long getLightLastscan() {
        return lightLastscan;
    }

    /**
	 * Sets the value of the lightLastscan property.
	 * @uml.property  name="lightLastscan"
	 */
    public void setLightLastscan(long value) {
        this.lightLastscan = value;
    }

    /**
	 * Gets the value of the lightMass property.
	 * @uml.property  name="lightMass"
	 */
    public float getLightMass() {
        return lightMass;
    }

    /**
	 * Sets the value of the lightMass property.
	 * @uml.property  name="lightMass"
	 */
    public void setLightMass(float value) {
        this.lightMass = value;
    }

    /**
	 * Gets the value of the heavyFirstscan property.
	 * @uml.property  name="heavyFirstscan"
	 */
    public long getHeavyFirstscan() {
        return heavyFirstscan;
    }

    /**
	 * Sets the value of the heavyFirstscan property.
	 * @uml.property  name="heavyFirstscan"
	 */
    public void setHeavyFirstscan(long value) {
        this.heavyFirstscan = value;
    }

    /**
	 * Gets the value of the heavyLastscan property.
	 * @uml.property  name="heavyLastscan"
	 */
    public long getHeavyLastscan() {
        return heavyLastscan;
    }

    /**
	 * Sets the value of the heavyLastscan property.
	 * @uml.property  name="heavyLastscan"
	 */
    public void setHeavyLastscan(long value) {
        this.heavyLastscan = value;
    }

    /**
	 * Gets the value of the heavyMass property.
	 * @uml.property  name="heavyMass"
	 */
    public float getHeavyMass() {
        return heavyMass;
    }

    /**
	 * Sets the value of the heavyMass property.
	 * @uml.property  name="heavyMass"
	 */
    public void setHeavyMass(float value) {
        this.heavyMass = value;
    }

    /**
	 * Gets the value of the massTol property.
	 * @uml.property  name="massTol"
	 */
    public float getMassTol() {
        return massTol;
    }

    /**
	 * Sets the value of the massTol property.
	 * @uml.property  name="massTol"
	 */
    public void setMassTol(float value) {
        this.massTol = value;
    }

    /**
	 * Gets the value of the ratio property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="ratio"
	 */
    public String getRatio() {
        return ratio;
    }

    /**
	 * Sets the value of the ratio property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="ratio"
	 */
    public void setRatio(String value) {
        this.ratio = value;
    }

    /**
	 * Gets the value of the heavy2LightRatio property.
	 * @return  possible object is {@link String  }  
	 * @uml.property  name="heavy2LightRatio"
	 */
    public String getHeavy2LightRatio() {
        return heavy2LightRatio;
    }

    /**
	 * Sets the value of the heavy2LightRatio property.
	 * @param value  allowed object is {@link String  }  
	 * @uml.property  name="heavy2LightRatio"
	 */
    public void setHeavy2LightRatio(String value) {
        this.heavy2LightRatio = value;
    }

    /**
	 * Gets the value of the lightArea property.
	 * @uml.property  name="lightArea"
	 */
    public float getLightArea() {
        return lightArea;
    }

    /**
	 * Sets the value of the lightArea property.
	 * @uml.property  name="lightArea"
	 */
    public void setLightArea(float value) {
        this.lightArea = value;
    }

    /**
	 * Gets the value of the heavyArea property.
	 * @uml.property  name="heavyArea"
	 */
    public float getHeavyArea() {
        return heavyArea;
    }

    /**
	 * Sets the value of the heavyArea property.
	 * @uml.property  name="heavyArea"
	 */
    public void setHeavyArea(float value) {
        this.heavyArea = value;
    }

    /**
	 * Gets the value of the decimalRatio property.
	 * @return  possible object is {@link BigDecimal  }  
	 * @uml.property  name="decimalRatio"
	 */
    public BigDecimal getDecimalRatio() {
        return decimalRatio;
    }

    /**
	 * Sets the value of the decimalRatio property.
	 * @param value  allowed object is {@link BigDecimal  }  
	 * @uml.property  name="decimalRatio"
	 */
    public void setDecimalRatio(BigDecimal value) {
        this.decimalRatio = value;
    }

}
