package domain;

public class PepNovoPTMFactory {
    public ModifiedAminoAcid createPTM(String name){
        ModifiedAminoAcidFactory modifiedAminoAcidFactory = new ModifiedAminoAcidFactory();

        switch (name){
            case "C+57":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("C",57.021464,null);
            case "H+57":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("H",57.021464,null);
            case "D+57":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("D",57.021464,null);
            case "E+57":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("E",57.021464,null);
            case "C-57":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("C",-57.021,null);
            case "W+12":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("W",12.0,null);
            case "W+4":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("W",3.994915,null);
            case "S+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("S",37.955882,null);
            case "K+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("K",37.955882,null);
            case "N+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("N",37.955882,null);
            case "P+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("P",37.955882,null);
            case "L+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("L",37.955882,null);
            case "R+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("R",37.955882,null);
            case "V+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("V",37.955882,null);
            case "I+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("I",37.955882,null);
            case "E+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("E",37.955882,null);
            case "M+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("M",37.955882,null);
            case "D+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("D",37.955882,null);
            case "G+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("G",37.955882,null);
            case "A+38":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("A",37.955882,null);
            case "R+55":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("R",55.053433,null);
            case "Q+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("Q",21.981943,null);
            case "V+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("V",21.981943,null);
            case "P+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("P",21.981943,null);
            case "N+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("N",21.981943,null);
            case "Y+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("Y",21.981943,null);
            case "T+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("T",21.981943,null);
            case "H+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("H",21.981943,null);
            case "D+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("D",21.981943,null);
            case "E+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("E",21.981943,null);
            case "S+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("S",21.981943,null);
            case "F+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("F",21.981943,null);
            case "A+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("A",21.981943,null);
            case "M+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("M",21.981943,null);
            case "I+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("I",21.981943,null);
            case "L+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("L",21.981943,null);
            case "G+22":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("G",21.981943,null);
            case "P+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("P",43.005814,null);
            case "A+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("A",43.005814,null);
            case "N+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("N",43.005814,null);
            case "M+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("M",43.005814,null);
            case "E+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("E",43.005814,null);
            case "T+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("T",43.005814,null);
            case "G+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("G",43.005814,null);
            case "D+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("D",43.005814,null);
            case "L+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("L",43.005814,null);
            case "F+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("F",43.005814,null);
            case "I+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("I",43.005814,null);
            case "Q+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("Q",43.005814,null);
            case "S+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("S",43.005814,null);
            case "V+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("V",43.005814,null);
            case "K+43":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("K",43.005814,null);
            case "E-18":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("E",-18.010565,null);
            case "D-18":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("D",-18.010565,null);
            case "S-18":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("S",-18.010565,null);
            case "T-18":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("T",-18.010565,null);
            case "K+28":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("K",28.031300,null);
            case "M+32":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("M",31.989829,null);
            case "W+32":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("W",31.989829,null);
            case "S+28":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("S",27.994915,null);
            case "T+28":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("T",27.994915,null);
            case "M+16":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("M",15.994915,null);
            case "H+16":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("H",15.994915,null);
            case "W+16":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("W",15.994915,null);
            case "D+16":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("D",15.994915,null);
            case "K+16":
                return  modifiedAminoAcidFactory.createModifiedAminoAcid("K",15.994915,null);
            case "N+16":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("N",15.994915,null);
            case "P+16":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("P",15.994915,null);
            case "N+1":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("N",0.984016,null);
            case "Q+1":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("Q",0.984016,null);
            case "C+14":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("C",14.015650,null);
            case "H+14":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("H",14.015650,null);
            case "K+14":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("K",14.015650,null);
            case "N+14":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("N",14.015650,null);
            case "Q+14":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("Q",14.015650,null);
            case "R+14":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("R",14.015650,null);
            case "S+80":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("S",79.966331,null);
            case "T+80":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("T",79.966331,null);
            case "Y+80":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("Y",79.966331,null);
            case "Q-17":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("Q",-17.026549,null);
            case "N-17":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("N",-17.026549,null);
            case "$-1":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("C_TERM",-0.984016,null);
            case "$+2":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("C_TERM",2.004246,null);
            case "^+14":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("N_TERM",14.015650,null);
            case "^+42":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("N_TERM",42.010565,null);
            case "$^+57":
                return modifiedAminoAcidFactory.createModifiedAminoAcid("N_TERM",57.0214,null);
            default:
                return null;
        }
    }
}
